server:
  port: 8089

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path= /api/product

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path= /api/inventory**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path= /api/order

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path= /api/cart**

        - id: service-registry
          uri: lb://service-registry
          predicates:
            - Path= /api/eureka/**

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/