server:
  port: 8085
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/products?authSource=admin

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/