server:
  port: 8088

spring:
  application:
    name: cart-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27018/cart?authSource=admin

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/